import type { Metadata } from 'next'
import Cards from './components/compCards'
import Hero from './components/compHero'

export const metadata: Metadata = {
  title: 'ByteBank - Página Inicial',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <section>
      <Hero />
      <Cards />
    </section>
  )
}
