import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'ByteBank | Dashboard',
  description: 'Generated by create next app',
}

export default function Home() {
  return <section>Oi</section>
}
